#include "crc_tables_crc16.h"

/*
List of lookup tables for CRC-16. By using lookup table, you will be precomputing the "computation intensive" part of the CRC calculation for every possible byte value and
store that result in the table. Then when you encounter a particular value, you look up the precomputed result for it, and just accumulate it with some XORing and shifting.
Simple XOR and shifting is much faster than the division and modulo operations that are used in the CRC calculation.

- CRC-16/ARC
- CRC-16/AUG-CCITT
- CRC-16/BUYPASS
- CRC-16/CCITT-FALSE
- CRC-16/CDMA2000
- CRC-16/DDS-110
- CRC-16/DECT-R
- CRC-16/DECT-X
- CRC-16/DNP
- CRC-16/EN-13757
- CRC-16/GENIBUS
- CRC-16/KERMIT
- CRC-16/MAXIM
- CRC-16/MCRF4XX
- CRC-16/MODBUS
- CRC-16/RIELLO
- CRC-16/T10-DIF
- CRC-16/TELEDISK
- CRC-16/TMS37157
- CRC-16/USB
- CRC-16/X-25
- CRC-16/XMODEM
- CRC-A

*/

/*
The following lookup tables are generated by the python script `./tools/precompute_crc_tables_crc16.py`.
The script is located in the `tools` directory of the repository.
The script generates the lookup tables for the following CRC-16 algorithms:
- CRC-16/ARC
- CRC-16/AUG-CCITT
- CRC-16/BUYPASS
- CRC-16/CCITT-FALSE |
- CRC-16/CDMA2000
- CRC-16/DDS-110
- CRC-16/DECT-R
- CRC-16/DECT-X
- CRC-16/DNP
- CRC-16/EN-13757
- CRC-16/GENIBUS
- CRC-16/KERMIT
- CRC-16/MAXIM
- CRC-16/MCRF4XX
- CRC-16/MODBUS
- CRC-16/RIELLO
- CRC-16/T10-DIF
- CRC-16/TELEDISK
- CRC-16/TMS37157
- CRC-16/USB
- CRC-16/X-25
- CRC-16/XMODEM
- CRC-A
*/

